print("Hola Mundo")
print(100+50)
print("Me encanta estudiar Python")
print("Estudiar con 'Python Total' es super divertido")
print(555)
print("Hola " + 'Guille')
print("Hola" + ' Guille')
print("Hola" +" "+ 'Guille')
print("Esta es una línea\nY esta es otra línea")
print("\tEsta es la tercera línea")
print('This isn\'t a number')
print("Este signo \\ es una barra invertida")
print("Línea 1\nLínea 2\nLínea 3")
print("A\tB\tC\nD\tE\tF\nG\tH\tI")
print("Barra normal: /")
print("Barra invertida: \\")